# API KEYS
OPENAI_API_KEY: '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'

# HYPERPARAMS
CHUNK_SIZE: 512
CHUNK_OVERLAP: 25
TOP_K: 10

#DIRECTORY
LOG_DIR: 'logs'

# COMMUNICATION
HOST: 'localhost'
PORT: 8000