name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install src package
      run: pip install -e .

    # Run tests
    - name: Run tests
      run: python -m unittest discover -s test

    # Run linting
    - name: Run linting
      run: flake8 src test